server:
  port: 80
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  mvc:
    view:
      prefix: classpath:/templates/,classpath:/static/
  thymeleaf:
    cache: false
  freemarker:
    cache: false
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: zjd
    password: Cpic12345
    driver-class-name: oracle.jdbc.driver.OracleDriver
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 2000s
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    lettuce:
      shutdown-timeout: 100ms
logging:
  level:
    com.kikyc.utils: debug
mybatis:
  mapper-locations: classpath:mapping/*.xml
  config-locations: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.kikyc.utils.entity
user:
  id: 01
  name: 张
  sex: 男
  money: 10
  grade: 1